languageCode = "en"
languageName = "English"
weight = 1
title = "Tracksy's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Read at our architectural decisions for the project."
dateFormat = "2 January 2006"
logo = "tracksy-blog.png"
secondaryLogo = "tracksy-blog.png"

["params.author"]
name = "Tracksy team"
image = "tracksy-blog.png"
headline = ""
