colorScheme = "forest"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
firebase = { }
fathomAnalytics = { }
verification = { }
defaultFeaturedImage = "tracksy-blog.png"
highlightCurrentMenuArea = true
smartTOC = true

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true
showMenu = false

[homepage]
layout = "page"
showRecent = true
showRecentItems = "5"
showMoreLink = false
showMoreLinkDest = "https://github.com/Gudsfile/tracksy"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "thumbAndBackground"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [
  "linkedin",
  "bluesky",
  "reddit",
  "mastodon",
  "twitter",
  "whatsapp",
  "telegram",
  "email"
]
showRelatedContent = false
showZenMode = true

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
layoutBackgroundHeaderSpace = "200"

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true

[term]
groupByYear = true
