name: Deploy App in Preview

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  app:
    name: Deploy App Preview
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-latest
    env:
      PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      PUBLIC_DEMO_JSON_URL: ${{ vars.PUBLIC_DEMO_JSON_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: false

      - name: Setup toolchains
        run: moon setup

      - name: Build project
        run: moon run app:build

      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
          projectId: tracksy-app
          entryPoint: ./app
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
