name: Build App

on:
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy-preview.yml"

permissions:
  contents: read

jobs:
  app:
    name: Build audit and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      PUBLIC_DEMO_JSON_URL: ${{ vars.PUBLIC_DEMO_JSON_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node 22
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Audit dependencies
        continue-on-error: true
        run: pnpm audit --prod

      - name: Check format
        run: pnpm run format:check

      - name: Check Lint
        run: pnpm run lint

      - name: Check test
        run: pnpm run test:coverage

      - name: Build project
        run: pnpm run build
