name: Build App

on:
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/app-build.yml"
      - ".moon/toolchains.yml"

permissions:
  contents: read

jobs:
  app:
    name: Build audit and test
    runs-on: ubuntu-latest
    env:
      PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      PUBLIC_DEMO_JSON_URL: ${{ vars.PUBLIC_DEMO_JSON_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: false

      - name: Setup toolchains
        run: moon setup

      - name: Audit dependencies
        run: moon run app:audit

      - name: Check format
        run: moon run app:format-check

      - name: Check Lint
        run: moon run app:lint

      - name: Check test
        run: moon run app:test-coverage

      - name: Build project
        run: moon run app:build
