name: Deploy Tracksy App to live

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - ".github/workflows/app-deploy-live.yml"
      - ".moon/toolchains.yml"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  checks: write
  actions: read

# Allow one concurrent deployment
concurrency:
  group: gh-pages-deploy
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  app:
    name: Deploy App to Live
    runs-on: ubuntu-latest
    env:
      PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      PUBLIC_DEMO_JSON_URL: ${{ vars.PUBLIC_DEMO_JSON_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: false

      - name: Setup toolchains
        run: moon setup

      - name: Audit dependencies
        run: moon run app:audit

      - name: Check format
        run: moon run app:format-check

      - name: Check Lint
        run: moon run app:lint

      - name: Check test
        run: moon run app:test-coverage

      - name: Build project
        run: moon run app:build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./app/dist
          destination_dir: .
          keep_files: true
  e2e-tests:
    needs: app
    uses: ./.github/workflows/e2e.yml
    with:
      baseUrl: "https://gudsfile.github.io/"
      testPath: "/tracksy"
    secrets: inherit
