name: Deploy Tracksy App in Preview

on:
  pull_request: # Github Actions only handles theses types. It cleans associated preview when a PR is closed.
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - "app/**"
      - ".github/workflows/app-deploy-preview.yml"
      - ".moon/toolchains.yml"
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  id-token: write
  pages: write
  pull-requests: write
  actions: read

# Allow one concurrent deployment
concurrency: preview-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  deploy-preview:
    name: Deploy App Preview
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.deploy_preview.outputs.preview-url }}
    env:
      PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      PUBLIC_DEMO_JSON_URL: ${{ vars.PUBLIC_DEMO_JSON_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
          auto-setup: true
          cache: true

      - name: Build project
        run: moon run app:build
        env:
          BASE_PATH: /tracksy/pr-preview/pr-${{ github.event.pull_request.number }}

      - name: Deploy preview
        id: deploy_preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./app/dist
          deploy-commit-message: "chore(): deploy Tracksy App Preview for PR #${{ github.event.number }}"
          remove-commit-message: "chore(): remove Tracksy App Preview for PR #${{ github.event.number }}"

  e2e-tests:
    needs: deploy-preview
    uses: ./.github/workflows/e2e.yml
    with:
      baseUrl: ${{ needs.deploy-preview.outputs.preview-url}}
      testPath: /tracksy/pr-preview/pr-${{ github.event.pull_request.number }}
    secrets: inherit
