name: Audit datasets generator

on:
  push:
    branches: ["main"]
    paths:
      - "synthetic-datasets/**"
      - ".github/workflows/datasets-test-synthetic.yml"
      - ".moon/toolchains.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "synthetic-datasets/synthetic_datasets/**/*.py"
      - "synthetic-datasets/pyproject.toml"
      - "synthetic-datasets/uv.lock"
      - "synthetic-datasets/moon.yml"
      - ".github/workflows/datasets-test-synthetic.yml"

permissions:
  contents: read

jobs:
  build:
    name: Audit
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./synthetic-datasets

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: false

      - name: Setup toolchains
        run: moon setup

      - name: Run format check
        run: moon run synthetic-datasets:format-check

      - name: Run lint check
        run: moon run synthetic-datasets:lint

      - name: Run type check
        run: moon run synthetic-datasets:typecheck

      - name: Run tests
        run: moon run synthetic-datasets:test
